#!/bin/bash

# AgentForge - GitHub 发布命令
# 由于网络问题，请手动执行这些命令

echo "🚀 AgentForge v0.1.0 - GitHub 发布命令"
echo "======================================"
echo ""
echo "请在终端中执行以下命令："
echo ""
echo "# 1. 进入项目目录"
echo "cd ~/Downloads/world-of-claudecraft"
echo ""
echo "# 2. 推送主分支（可能需要输入 GitHub 用户名和密码/token）"
echo "git push origin main"
echo ""
echo "# 3. 推送标签"
echo "git push origin v0.1.0 --force"
echo ""
echo "# 4. 在 GitHub 创建 Release"
echo "# 访问：https://github.com/Summonair/world-of-claudecraft/releases/new"
echo "# - Choose tag: v0.1.0"
echo "# - Title: AgentForge v0.1.0 - MVP Release 🎉"
echo "# - Description: 复制 GITHUB_RELEASE_COPY.txt 内容"
echo "# - 点击 Publish release"
echo ""
echo "# 5. 更新仓库名称（可选）"
echo "# Settings → General → Repository name → agentforge"
echo ""
echo "=================================="
echo "✅ 所有文件已准备就绪！"
echo "=================================="
