/**
 * PDF Export Utility
 * v2.4.0 Phase 1.4 - 报表导出功能
 */
import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'

export interface ExportOptions {
  filename?: string
  quality?: number
  orientation?: 'portrait' | 'landscape'
  format?: 'a4' | 'letter'
}

/**
 * 导出Dashboard为PDF
 */
export async function exportDashboardToPdf(
  elementId: string = 'dashboard',
  options: ExportOptions = {}
): Promise<void> {
  const {
    filename = 'AgentForge-Dashboard-Report',
    quality = 0.95,
    orientation = 'portrait',
    format = 'a4'
  } = options

  try {
    // 获取要导出的元素
    const element = document.getElementById(elementId)
    if (!element) {
      throw new Error(`Element with id "${elementId}" not found`)
    }

    // 显示加载提示
    const loadingToast = showLoadingToast('正在生成PDF...')

    // 生成canvas
    const canvas = await html2canvas(element, {
      scale: 2, // 提高清晰度
      useCORS: true,
      logging: false,
      backgroundColor: '#0a0a0a' // 匹配深色主题
    })

    // 创建PDF
    const imgWidth = orientation === 'portrait' ? 210 : 297 // A4尺寸 (mm)
    const imgHeight = orientation === 'portrait' ? 297 : 210

    const pdf = new jsPDF({
      orientation,
      unit: 'mm',
      format
    })

    // 计算图片尺寸以适应页面
    const canvasWidth = canvas.width
    const canvasHeight = canvas.height
    const ratio = canvasWidth / canvasHeight

    let pdfWidth = imgWidth
    let pdfHeight = imgWidth / ratio

    if (pdfHeight > imgHeight) {
      pdfHeight = imgHeight
      pdfWidth = imgHeight * ratio
    }

    // 添加图片到PDF
    const imgData = canvas.toDataURL('image/jpeg', quality)
    pdf.addImage(imgData, 'JPEG', 0, 0, pdfWidth, pdfHeight)

    // 添加页脚
    const timestamp = new Date().toLocaleString('zh-CN')
    pdf.setFontSize(8)
    pdf.setTextColor(128, 128, 128)
    pdf.text(
      `Generated by AgentForge v2.4.0 | ${timestamp}`,
      10,
      imgHeight - 5
    )

    // 保存PDF
    pdf.save(`${filename}-${Date.now()}.pdf`)

    // 移除加载提示
    hideLoadingToast(loadingToast)

    // 显示成功提示
    showSuccessToast('PDF导出成功！')
  } catch (error) {
    console.error('PDF export failed:', error)
    showErrorToast('PDF导出失败: ' + (error as Error).message)
    throw error
  }
}

/**
 * 导出特定图表为PDF
 */
export async function exportChartToPdf(
  chartId: string,
  options: ExportOptions = {}
): Promise<void> {
  return exportDashboardToPdf(chartId, {
    ...options,
    filename: options.filename || `Chart-${chartId}`
  })
}

/**
 * 导出多个页面为单个PDF
 */
export async function exportMultiPagePdf(
  elementIds: string[],
  options: ExportOptions = {}
): Promise<void> {
  const {
    filename = 'AgentForge-Full-Report',
    quality = 0.95,
    orientation = 'portrait',
    format = 'a4'
  } = options

  try {
    const loadingToast = showLoadingToast(`正在生成${elementIds.length}页PDF...`)

    const pdf = new jsPDF({
      orientation,
      unit: 'mm',
      format
    })

    const imgWidth = orientation === 'portrait' ? 210 : 297
    const imgHeight = orientation === 'portrait' ? 297 : 210

    for (let i = 0; i < elementIds.length; i++) {
      const element = document.getElementById(elementIds[i])
      if (!element) {
        console.warn(`Element ${elementIds[i]} not found, skipping`)
        continue
      }

      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#0a0a0a'
      })

      const canvasWidth = canvas.width
      const canvasHeight = canvas.height
      const ratio = canvasWidth / canvasHeight

      let pdfWidth = imgWidth
      let pdfHeight = imgWidth / ratio

      if (pdfHeight > imgHeight) {
        pdfHeight = imgHeight
        pdfWidth = imgHeight * ratio
      }

      if (i > 0) {
        pdf.addPage()
      }

      const imgData = canvas.toDataURL('image/jpeg', quality)
      pdf.addImage(imgData, 'JPEG', 0, 0, pdfWidth, pdfHeight)

      // 添加页码
      pdf.setFontSize(8)
      pdf.setTextColor(128, 128, 128)
      pdf.text(
        `Page ${i + 1} of ${elementIds.length}`,
        imgWidth - 30,
        imgHeight - 5
      )
    }

    pdf.save(`${filename}-${Date.now()}.pdf`)

    hideLoadingToast(loadingToast)
    showSuccessToast('PDF导出成功！')
  } catch (error) {
    console.error('Multi-page PDF export failed:', error)
    showErrorToast('PDF导出失败')
    throw error
  }
}

/**
 * Toast提示函数 (简化版，实际应使用NotificationCenter)
 */
function showLoadingToast(message: string): string {
  const id = `toast-${Date.now()}`
  // TODO: 集成实际的通知系统
  console.log(`[Loading] ${message}`)
  return id
}

function hideLoadingToast(id: string): void {
  console.log(`[Hide] ${id}`)
}

function showSuccessToast(message: string): void {
  console.log(`[Success] ${message}`)
}

function showErrorToast(message: string): void {
  console.error(`[Error] ${message}`)
}

/**
 * 创建邮件分享链接
 */
export function createEmailShareLink(
  subject: string = 'AgentForge Dashboard Report',
  body: string = ''
): string {
  const encodedSubject = encodeURIComponent(subject)
  const encodedBody = encodeURIComponent(
    body ||
    `Hi,\n\n` +
    `Please find the attached AgentForge Dashboard Report.\n\n` +
    `Generated at: ${new Date().toLocaleString()}\n` +
    `Powered by AgentForge v2.4.0\n\n` +
    `Best regards`
  )

  return `mailto:?subject=${encodedSubject}&body=${encodedBody}`
}

/**
 * 导出数据为CSV
 */
export function exportDataToCsv(
  data: any[],
  filename: string = 'data'
): void {
  if (!data || data.length === 0) {
    showErrorToast('没有数据可导出')
    return
  }

  try {
    // 获取所有键作为表头
    const headers = Object.keys(data[0])

    // 创建CSV内容
    const csvContent = [
      headers.join(','), // 表头
      ...data.map(row =>
        headers.map(header => {
          const value = row[header]
          // 处理包含逗号的值
          return typeof value === 'string' && value.includes(',')
            ? `"${value}"`
            : value
        }).join(',')
      )
    ].join('\n')

    // 创建Blob并下载
    const blob = new Blob(['\ufeff' + csvContent], {
      type: 'text/csv;charset=utf-8;'
    })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${filename}-${Date.now()}.csv`
    link.click()
    URL.revokeObjectURL(url)

    showSuccessToast('CSV导出成功！')
  } catch (error) {
    console.error('CSV export failed:', error)
    showErrorToast('CSV导出失败')
  }
}

/**
 * 导出数据为JSON
 */
export function exportDataToJson(
  data: any,
  filename: string = 'data'
): void {
  try {
    const jsonContent = JSON.stringify(data, null, 2)
    const blob = new Blob([jsonContent], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${filename}-${Date.now()}.json`
    link.click()
    URL.revokeObjectURL(url)

    showSuccessToast('JSON导出成功！')
  } catch (error) {
    console.error('JSON export failed:', error)
    showErrorToast('JSON导出失败')
  }
}

export default {
  exportDashboardToPdf,
  exportChartToPdf,
  exportMultiPagePdf,
  createEmailShareLink,
  exportDataToCsv,
  exportDataToJson
}
