import type { AgentItem, Category } from '../types'
import { CATEGORY_ICONS } from '../types'

/**
 * Generate combined agents.md from equipped items
 */
export function generateMarkdown(items: AgentItem[]): string {
  if (items.length === 0) {
    return '# Agent Configuration\n\nNo components equipped.'
  }

  const sections: string[] = []

  // Header
  sections.push('# Agent Configuration')
  sections.push('')
  sections.push(`> Generated by Agent Builder on ${new Date().toLocaleDateString()}`)
  sections.push('')

  // Group items by category
  const categorized: Record<Category, AgentItem[]> = {
    roles: [],
    skills: [],
    behaviors: [],
    personalities: [],
    constraints: [],
    contexts: [],
    formats: [],
    tools: []
  }

  for (const item of items) {
    categorized[item.category].push(item)
  }

  // Output categories in logical order
  const categoryOrder: Category[] = [
    'roles',
    'personalities',
    'behaviors',
    'skills',
    'contexts',
    'constraints',
    'formats',
    'tools'
  ]

  for (const category of categoryOrder) {
    const categoryItems = categorized[category]
    if (categoryItems.length === 0) continue

    const icon = CATEGORY_ICONS[category]
    const title = category.charAt(0).toUpperCase() + category.slice(1)

    sections.push(`## ${icon} ${title}`)
    sections.push('')

    for (const item of categoryItems) {
      // Clean up content - remove leading # heading if present (we'll use item name)
      let content = item.content.trim()

      // If content starts with a # heading that matches the name, remove it
      const headingMatch = content.match(/^#\s+(.+)$/m)
      if (headingMatch && headingMatch[1].toLowerCase() === item.name.toLowerCase()) {
        content = content.replace(/^#\s+.+\n*/m, '').trim()
      }

      sections.push(`### ${item.name}`)
      sections.push('')
      sections.push(content)
      sections.push('')
    }
  }

  // Stats footer
  const totalTokens = items.reduce((sum, item) => sum + item.tokens, 0)
  sections.push('---')
  sections.push('')
  sections.push(`*Total tokens: ~${totalTokens}*`)

  return sections.join('\n')
}

/**
 * Generate a summary of equipped items
 */
export function generateSummary(items: AgentItem[]): string {
  if (items.length === 0) return 'No components equipped'

  const counts: Partial<Record<Category, number>> = {}
  let totalTokens = 0

  for (const item of items) {
    counts[item.category] = (counts[item.category] || 0) + 1
    totalTokens += item.tokens
  }

  const parts: string[] = []
  for (const [category, count] of Object.entries(counts)) {
    const icon = CATEGORY_ICONS[category as Category]
    parts.push(`${icon} ${count}`)
  }

  return `${parts.join(' • ')} | ~${totalTokens} tokens`
}
